services:
  ingest-service:
    build: ./ingest-service
    ports:
      - "8080:8080"

  extract-service:
    build: ./extract-service
    ports:
      - "8081:8080"

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    stop_grace_period: 0s

