#!/bin/bash

# LOG_FILE=/var/log/demoapp/demoapp.log
LOG_FILE=${1:-/var/log/demoapp/demoapp.log}
LOG_VARIANT=${2:-production}
LOG_APPNAME=${3:-demoapp}

echo "Writing logs to $LOG_FILE..."

trap "echo 'Exiting...'; exit;" SIGINT SIGTERM

while true; do
  # Generate a random log entry
  TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
  LEVEL=$(shuf -n 1 -e "DEBUG" "INFO" "WARN" "ERROR" "FATAL")

  if [[ "$LOG_VARIANT" == "production" ]]; then
    MESSAGE=$(shuf -n 1 -e "Live data loaded" "User logged into production system" "Credit card processed in live" "Live payment made" "Payment made to production team" "Security alert in prod" "System rebooted in live region")
  elif [[ "$LOG_VARIANT" == "development" ]]; then
    MESSAGE=$(shuf -n 1 -e "Development completed" "Tests failed" "All tests passed" "Code developed" "Building code in development" "Pipeline development running" "Unknown development error" "Bundle wiring exception in code development" "System rebooted in development")
  else
    echo "Invalid log variant: $LOG_VARIANT"
    exit 1
  fi

  # MESSAGE=$(shuf -n 1 -e "User login successful" "Database connection lost" "Invalid input received" "Server timeout" "Unknown error occurred" "Sandwiches are ready" "Security patch installed" "Security alert received" "System reboot required")
  
  # Write the log entry to the file
  echo "$TIMESTAMP [$LEVEL] demoapp-$LOG_VARIANT $MESSAGE" >> $LOG_FILE
  
  # Wait for a random amount of time before generating the next log entry
  sleep $(shuf -i 0-3 -n 1)
done
