version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # REALM_NAME: ${REALM_NAME}
      # CLIENT_ID: ${CLIENT_ID}
      # CLIENT_SECRET: ${CLIENT_SECRET}
      # GRAFANA_URL: http://grafana:3000
    ports:
      - "8080:8080"
    command: start-dev
    # volumes:
    #   - ./keycloak-setup.sh:/opt/keycloak/keycloak-setup.sh:z
    # entrypoint: /bin/sh
    # command: 
    #   - /bin/sh
    #   - -c
    #   - |
    #     /opt/keycloak/bin/kc.sh start-dev &
    #     sleep 30
    #     /opt/keycloak/keycloak-setup.sh

  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: "debug"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://localhost:8080/realms/${REALM_NAME}/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://keycloak:8080/realms/${REALM_NAME}/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://keycloak:8080/realms/${REALM_NAME}/protocol/openid-connect/userinfo"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(realm_access.roles[*], 'admin') && 'Admin' || contains(realm_access.roles[*], 'editor') && 'Editor' || 'Viewer'"
    depends_on:
      - keycloak

volumes:
  keycloak-data:
  grafana-data:


