apiVersion: 1

datasources:
  - name: victoria-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
