{
 "title": "Loki rate limit demo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Loki rate limit configuration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "source": "url",
     "type": "uql",
     "uql": "parse-yaml\n| jsonata \"{ \\\"ingestion_rate_mb\\\": $.limits_config.ingestion_rate_mb, \\\"ingestion_burst_size_mb\\\": $.limits_config.ingestion_burst_size_mb }\"\n| project kv()",
     "url": "http://loki:3100/config",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Alloy Loki write component - Dropped entries",
   "type": "timeseries",
   "description": "Shows the number of entries (requests) that were dropped by Alloy's Loki write component. \n\nThis should remain at 0 to ensure that no logs have been dropped.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_write_dropped_entries_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alloy Loki write component - request rate",
   "type": "timeseries",
   "description": "This shows the per-second rate of requests from Alloy to the Loki API. ",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_write_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki - Discarded (rejected) samples (lines) by reason",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "targets": [
    {
     "expr": "rate(loki_discarded_samples_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki - Distributor ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}