---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: petshop

scrape_configs:
  - job_name: floglogs
    static_configs:
    - targets:
        - localhost
      labels:
        job: floglogs
        __path__: /var/log/flog/*log
