apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: order-api
          image: localhost/order-api:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: order-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: demo-app
spec:
  selector:
    app: order-api
  ports:
    - port: 8080
      targetPort: 8080
