receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

extensions:
  sigv4auth:
    region: us-east-1
    service: logs
  basicauth/grafana_cloud:
    client_auth:
      username: "${env:GRAFANA_CLOUD_OTLP_USERNAME}"
      password: "${env:GRAFANA_CLOUD_ACCESS_POLICY_TOKEN}"

processors:
  batch:
    timeout: 5s

exporters:
  debug:
    verbosity: detailed
    use_internal_logger: false
    output_paths: [stdout]

  # CloudWatch's native OTLP endpoint.
  otlphttp/cloudwatch:
    logs_endpoint: https://logs.us-east-1.amazonaws.com/v1/logs
    compression: gzip
    headers:
      x-aws-log-group: /otel/test-logs
      x-aws-log-stream: telemetrygen-stream-otlp  # this log stream needs to exist first
    auth:
      authenticator: sigv4auth

  # Grafana Cloud's OTLP endpoint. It appends /v1/logs to the base URL.
  otlphttp/grafana_cloud:
    endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}"
    auth:
      authenticator: basicauth/grafana_cloud

service:
  extensions: [sigv4auth, basicauth/grafana_cloud]
  telemetry:
    logs:
      level: debug
      development: true
      sampling:
        enabled: false
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/cloudwatch, otlphttp/grafana_cloud]
