{
 "title": "ECS Service Health dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {
     "query": "label_values(traces_target_info,job)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(traces_target_info{job=\"$service_name\"},deployment_environment)"
    }
   },
   {
    "name": "task_family",
    "label": "Task",
    "query": {
     "query": "label_values(traces_target_info{job=\"$service_name\"},aws_ecs_task_family)"
    }
   },
   {
    "name": "ecs_service",
    "label": "ECS Service name",
    "query": {
     "query": "label_values(traces_target_info{job=\"$service_name\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster ARN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Launch type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Availability zone",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  { "title": "Application layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Task resources",
   "type": "stat",
   "description": "Last known values for CPU, memory and storage for this task/service.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ecs-fargate-events-firehose\"} |= `service:$ecs_service` | json | detail_memory!=`` | keep detail_memory, detail_cpu, detail_launchType, detail_ephemeralStorage_sizeInGiB, detail_availabilityZone, detail_clusterArn",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, job, ) (rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$service_name\", deployment_environment=~\".*\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$service_name\", deployment_environment=~\".*\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (job) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$service_name\", deployment_environment=~\".*\"} [$__rate_interval])) by (job) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$service_name\", deployment_environment=~\".*\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$service_name\", deployment_environment=~\".*\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": {
    "content": "<a href=\"/a/grafana-app-observability-app\">Go to Application Observability</a>"
   }
  },
  { "title": "Infrastructure layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "ECS CPU Usage per Container",
   "type": "timeseries",
   "description": "Displays the CPU usage rate for each ECS container over time to monitor workload distribution and identify potential performance bottlenecks.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (container_name) (\n  rate(ecs_container_cpu_usage_seconds_total[5m])\n  * on(instance) group_left(family)\n  group(ecs_task_metadata_info{family=\"$task_family\"}) by (instance, family)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS CPU Usage by Instance",
   "type": "timeseries",
   "description": "Displays the CPU usage rate over time for each ECS instance, helping identify instances with high or abnormal CPU consumption.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(ecs_container_cpu_usage_seconds_total[5m])\n  * on(instance) group_left(family)\n  group(ecs_task_metadata_info{family=\"$task_family\"}) by (instance, family)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS Events for this service",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ecs-fargate-events-firehose\"} |= `service:$ecs_service` | json # | detail_reason!=`` | line_format `{{.detail_type}} - {{.detail_reason}}` # | detail_reason!=`` | keep detail_type, detail_eventName, detail_eventType, detail_reason, detail_lastStatus, detail_group, detail_stoppedReason",
     "maxLines": 100
    }
   ]
  }
 ]
}