global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
    metrics_path: '/metrics'
