services:
  app:
    build:
      context: app
    ports:
      - "8080:8080"
    volumes:
      - ./app/public:/var/www/html/public:z
      - ./app/src:/var/www/html/src:z
    environment:
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_SERVICE_NAME=rolldice-local
      - OTEL_PROPAGATORS=baggage,tracecontext

  db:
    image: docker.io/library/mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  alloy:
    image: docker.io/grafana/alloy:latest
    ports:
      - "4317:4317/tcp" # OTLP gRPC
      - "4318:4318/tcp" # OTLP HTTP
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_INSTANCE_ID=${GRAFANA_CLOUD_INSTANCE_ID}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    logging:
      driver: "json-file"

volumes:
  db-data:
