services:

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    stop_grace_period: 2s
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  mitmproxy:
    image: docker.io/mitmproxy/mitmproxy:12.2
    command: mitmdump --mode reverse:http://otel-lgtm:3000 -p 3001 --script /scripts/inject_errors.py
    ports:
      - "3001:3001"
    volumes:
      - ./mitmproxy:/scripts:z
    depends_on:
      - otel-lgtm
