config:
  data:
    # Run unprivileged on GKE. See:
    # https://grafana.com/docs/beyla/latest/setup/kubernetes/#deploy-beyla-unprivileged
    privileged: false

    discovery:
      instrument:
        - k8s_namespace: "*"

env:
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}"
  OTEL_EXPORTER_OTLP_METRICS_HEADERS: "Authorization=Basic ${GRAFANA_CLOUD_AUTH_STRING}"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}"
  OTEL_EXPORTER_OTLP_TRACES_HEADERS: "Authorization=Basic ${GRAFANA_CLOUD_AUTH_STRING}"
  BEYLA_NETWORK_METRICS: true
  BEYLA_OTEL_METRIC_FEATURES: "application_span,application_service_graph,application_host,application"
