apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: docker.io/curlimages/curl:latest
          command: ["/bin/sh", "/scripts/loadgen.sh"]
          env:
            - name: GATEWAY_URL
              value: http://gateway-api:8080
          volumeMounts:
            - name: script
              mountPath: /scripts
      volumes:
        - name: script
          configMap:
            name: loadgen-script
