version: "3.8"

services:
  # Service to instrument. Change it to any
  # other container that you want to instrument.
  goblog:
    image: docker.io/mariomac/goblog:dev
    ports:
      # Exposes port 18843, forwarding it to container port 8443
      - "18443:8443"

  autoinstrumenter:
    image: docker.io/grafana/beyla:3
    pid: host # "service:goblog"
    privileged: true
    depends_on:
      - goblog # Ensure the container doesn't start until goblog has started (so podman doesn't reject the goblog namespace)
    environment:
#      BEYLA_TRACE_PRINTER: text
      BEYLA_AUTO_TARGET_EXE: "/goblog*" # just instrument the /goblog program
      BEYLA_LOG_LEVEL: debug
#      BEYLA_OPEN_PORT: 8443 # Instrument anything which has the port 8443 opened
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-lgtm:4317"
    stop_grace_period: 2s

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    stop_grace_period: 2s
    environment:
      - ENABLE_LOGS_TEMPO=true
      - ENABLE_LOGS_OTELCOL=true
